<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="A preview about me and my R works">
	<meta name="author" content="Jules Noël">
	<meta name="generator" content="Hugo 0.76.4" />
	<title>Session 6: Homework 3 &middot; Portfolio website of Jules Noël</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Jules Noël</strong> <span>A data analytics work</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/projects">Projects</a></li>
            
                <li><a href="/projects/CV">My CV</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/projects" class="button special fit">Get Started</a></li>
            
            
                <li><a href="/" class="button fit">Log In</a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Session 6: Homework 3</h1>
                            </header>
                            
                            
<link href="/rmarkdown-libs/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/pagedtable/js/pagedtable.js"></script>


<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>We want to explore some statistics to analyze health patterns from the CDC.
Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns.</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15...
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;f...
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9...
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;n...
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Afr...
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88...
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71....
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did n...
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did ...
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, ...
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5...
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, ...
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;...</code></pre>
<p>Before we carry on with our analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<p>We can see that we have some missing responses in our data for each variable. Notably in weight, we are missing <strong>1,004</strong> responses from our 13,583 total responses in the data.</p>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>As a useful statistic to explore the health among a certain population, we will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, we will describe the distribution of weight.</p>
<pre class="r"><code># Plotting an histogram with counts of weights. 
ggplot(yrbss, aes(x = weight))+
      geom_histogram()</code></pre>
<p><img src="/projects/project4/index_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Plotting the distribution of the weight variable.
ggplot(yrbss, aes(x = weight))+
      geom_density()</code></pre>
<p><img src="/projects/project4/index_files/figure-html/eda_on_weight-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Creating new data frame with descreptive statistics.
descriptive_weight &lt;- yrbss %&gt;% 
  
  # Removing the missing values.
  filter(!is.na(weight)) %&gt;% 
  
  # Calculating the statistics of interest.
  summarise(
    
    # General ones
    mean_weight = mean(weight), 
    median_weight = median(weight),
    count=n(),
    
    # Distribution statistics
    sd_weight = sd(weight),
    min_weight = min(weight),
    max_weight = max(weight), 
    iqr_weight = iqr(weight), 
    t_critical = qt(0.975, count-1),
    se_weight = sd(weight)/sqrt(count),
    margin_of_error = t_critical * se_weight,
    weight_low = mean_weight - margin_of_error,
    weight_high = mean_weight + margin_of_error)

# Printing out descriptive_weight in a table
descriptive_weight %&gt;% tbl_df %&gt;% rmarkdown::paged_table()</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["mean_weight"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["median_weight"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["count"],"name":[3],"type":["int"],"align":["right"]},{"label":["sd_weight"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["min_weight"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["max_weight"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["iqr_weight"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["t_critical"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["se_weight"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["margin_of_error"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["weight_low"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["weight_high"],"name":[12],"type":["dbl"],"align":["right"]}],"data":[{"1":"67.9","2":"64.4","3":"12579","4":"16.9","5":"29.9","6":"181","7":"20","8":"1.96","9":"0.151","10":"0.295","11":"67.6","12":"68.2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The distribution of the weights is skewed to the right. We can see a high density between 60kg and 80kg.
The rationale behind the skeweness may be that the natural evolution of a human being will require a certain weight, then some factors can influence someone to gain more weight but it is not the case for the majority of the population studied.</p>
<p>The weight is often related to physical activity. It might thus be a good idea to examine the relationship between these two variables. Let’s have a simple boxplot.</p>
<pre class="r"><code>ggplot(data = na.omit(yrbss), 
  
  # Setting up the axes              
  aes(
    x=physically_active_7d, 
    y= weight,
    group = physically_active_7d )) +
  
  # Setting the type of graph
  geom_boxplot() + 
  
  # Setting our title and axes names.
  labs(title = &quot;Weight increase with physical activity&quot;,
       subtitle = &quot;Relation between weight and frequency of physical activity&quot;,
       caption = &quot;Source: Youth Risk Behavior Surveillance System (YRBSS)&quot;,
       x=&quot;Number of days with physical activity in a week&quot;, 
       y=&quot;Weight&quot;)+
  
  # Choosing our theme and adding the unit for our &quot;y&quot; variable.
  theme_bw() +
  scale_y_continuous(label = label_number(suffix = &quot;Kg&quot;))</code></pre>
<p><img src="/projects/project4/index_files/figure-html/unnamed-chunk-3-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We can see a slight increase in the weight along the level activity but we cannot yet know if the difference is significant.</p>
<p>Let’s create a new variable <code>physical_3plus</code>, which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise.</p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;% 
  mutate(physical_3plus = ifelse(physically_active_7d &gt;= 3, &quot;yes&quot;, &quot;no&quot;))

yrbss %&gt;% filter(!is.na(physical_3plus)) %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(count = n()) %&gt;% 
  mutate(prop= count/sum(count))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   physical_3plus count  prop
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;
## 1 no              4404 0.331
## 2 yes             8906 0.669</code></pre>
<p>Now we will provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week.</p>
<pre class="r"><code># Calculating the necessary statistics to have the 95% CI.
not_active_ci &lt;- yrbss %&gt;% 
  summarise (
    
    # Proportion of high schools that are *NOT* active for 3 or more days per week.
    proportion_not_active = 
      count(physical_3plus==&#39;no&#39;)/count(!is.na(physical_3plus)), 
    
    # Standard deviation of the proportion previously found.
    sd_not_active = 
      sqrt(proportion_not_active*(1-proportion_not_active)), 
    
    # Just the count
    count=
      n(),
    
    # Setting the confidence level (5% == 0.025 on both sides)
    z_critical =
      qnorm(0.975,0,1),
    
    # Calculating the standard error
    se_not_active = 
      sd_not_active/sqrt(count),
    
    # Calculating the margin of error
    margin_of_error = 
      z_critical * se_not_active,
    
    # Finding the low and high point of our CI at 95%
    ci_low = 
      proportion_not_active - margin_of_error,
    ci_high = 
      proportion_not_active + margin_of_error)

# Print out CI
not_active_ci %&gt;% 
  select(ci_low,ci_high)</code></pre>
<pre><code>## # A tibble: 1 x 2
##   ci_low ci_high
##    &lt;dbl&gt;   &lt;dbl&gt;
## 1  0.323   0.339</code></pre>
<p>We now repeat the boxplot but with our new variable <code>physical_3plus</code> vs. <code>weight</code>.</p>
<pre class="r"><code>  # Creating our graph
ggplot(data = na.omit(yrbss), 
  
  # Setting up the axes              
  aes(
    x=physical_3plus, 
    y= weight)) +
  
  # Setting the type of graph
  geom_boxplot() + 
  
  # Setting our title and axes names.
  labs(title = &quot;Sporty people are heavier&quot;, 
       x=&quot;Does sport more than 3 times a week?&quot;, 
       y=&quot;Weight&quot;)+
  
  # Choosing our theme and adding the unit for our &quot;y&quot; variable.
  theme_bw() +
  scale_y_continuous(label = label_number(suffix = &quot;Kg&quot;))</code></pre>
<p><img src="/projects/project4/index_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Creating a table with some precise statistics for complementary information
table_physical_3plus &lt;- yrbss %&gt;%
  
  # Filtering out the missing values
  filter(!is.na(physical_3plus)) %&gt;% 
  
  # Group by active or not high schools
  group_by(physical_3plus)%&gt;%
  
  # calculating the desired statistics
  summarise(
    
    # Mean
    mean_3plus = 
      mean(weight, na.rm = TRUE), 
    
    # Median
    median_3plus = 
      median(weight, na.rm = TRUE)
  )

# Output our table as a paged one for better design. 
table_physical_3plus %&gt;% tbl_df %&gt;% rmarkdown::paged_table()</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["physical_3plus"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean_3plus"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["median_3plus"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"no","2":"66.7","3":"62.6"},{"1":"yes","2":"68.4","3":"65.8"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>We were expecting the contrary relationship. Surprisingly, it seems that people having more than 3 days of physical activity per week have a superior weight that people who do not exercise as often. A few hypothesis could be explored. For example, muscle is heavier than fat and thus exercising could generate more muscle. The level of activity could be linked with other variables absent of our dataset such as diet.</p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean/SD, etc weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>graph_CI &lt;- yrbss %&gt;%
  
  #Grouping by active of not high schools
  group_by(physical_3plus) %&gt;%
  
  # Filtering out the missing values
  filter(!is.na(physical_3plus)) %&gt;% 
  
  # Calculating the necessary statistics for our CI
  summarise(
    
    # General ones
    mean_weight = 
      mean(weight, na.rm = TRUE),
            
    # Standard deviation and standard error
    sd_weight = 
      sd(weight, na.rm=TRUE),
    count = 
      n(),
    se_weight = 
      sd_weight/sqrt(count),
    
    # Critical value for 95% confidence level and margin of error        
    t_critical = 
      qt(0.975, count-1), 
    margin_of_error = 
      t_critical * se_weight,
    
    # calculating the confidence interval        
    Lower_limit = 
      mean_weight - t_critical * se_weight,
    Upper_limit = 
      mean_weight + t_critical * se_weight
             )

# Output as paged table for more clarity.
graph_CI %&gt;% tbl_df %&gt;% rmarkdown::paged_table()</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["physical_3plus"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean_weight"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sd_weight"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["count"],"name":[4],"type":["int"],"align":["right"]},{"label":["se_weight"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["t_critical"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["margin_of_error"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["Lower_limit"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["Upper_limit"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"no","2":"66.7","3":"17.6","4":"4404","5":"0.266","6":"1.96","7":"0.521","8":"66.2","9":"67.2"},{"1":"yes","2":"68.4","3":"16.5","4":"8906","5":"0.175","6":"1.96","7":"0.342","8":"68.1","9":"68.8"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Now we will test the difference to confirm our earlier observations.
Null hypothesis: The difference in means is equal to zero.
Alternative Hypothesis: The difference in means is not equal to zero.</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Let’s simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/projects/project4/index_files/figure-html/unnamed-chunk-9-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/projects/project4/index_files/figure-html/unnamed-chunk-10-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>A couple weeks ago, we analyzed some data on IMBD ratings. Today, we will explore if there is a clear difference in the ratings received between Tim Burton and Steven Spielberg.</p>
<p><strong>Our Null Hypothesis: The true difference in means is equal to 0.</strong></p>
<p><strong>Alternative hypothesis: The true difference in means is not equal to 0.</strong></p>
<p>To test this hypothesis, we will use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<pre class="r"><code># Now, we want to select the date that we will use which is the rating and the directors
IMBD &lt;- movies %&gt;% 
  select(rating, director) %&gt;% 
  
  # We also filtered by the two directors in question
  filter(director %in% c(&quot;Tim Burton&quot;, &quot;Steven Spielberg&quot;)) %&gt;% 

  # In order to compare both directors, we group by this variable
  group_by(director) %&gt;% 
  
  # To calculate the necessary information to run a hypothesis test we use summarise
  summarise (
         
          # General Statistics
          mean_rating = 
            mean(rating, na.rm = TRUE),
          sd_rating = 
            sd(rating, na.rm=TRUE),
          count = n(),
         
          # CI Statistics
           se_rating = 
            sd_rating/sqrt(count),
          t_critical = 
            qt(0.975, count-1), 
          margin_of_error = 
            t_critical * se_rating,
          lower = 
            mean_rating - t_critical * se_rating,
          upper = 
            mean_rating + t_critical * se_rating
            )


# This line exhibits our calculations
IMBD %&gt;% tbl_df %&gt;% rmarkdown::paged_table()</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["director"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean_rating"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sd_rating"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["count"],"name":[4],"type":["int"],"align":["right"]},{"label":["se_rating"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["t_critical"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["margin_of_error"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["lower"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["upper"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"Steven Spielberg","2":"7.57","3":"0.695","4":"23","5":"0.145","6":"2.07","7":"0.301","8":"7.27","9":"7.87"},{"1":"Tim Burton","2":"6.93","3":"0.749","4":"16","5":"0.187","6":"2.13","7":"0.399","8":"6.53","9":"7.33"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code># Now we are going to replicate the graph

graph_directors &lt;- 
  
  ggplot(IMBD, 
  aes(
    x= mean_rating,
    y = reorder(director,mean_rating)))+
  geom_point()+
  theme_bw() +
  theme(legend.position = &quot;none&quot;)+
  
  # The next tree lines include the mean ratings and the upper and lower boundaries of the CI
  geom_text(aes(label = round(mean_rating, 2)), size = 6, hjust = 0.5,vjust = -1)+
  
  geom_text(aes(label = round(lower, 2)), hjust = 6, vjust = -2) +
  geom_text(aes(label = round(upper, 2)), hjust = -5.5, vjust = -2) +
  
  # This line includes the error bar 
  geom_errorbar(aes(xmin = lower, 
                    xmax = upper, 
                    colour = director, 
                    fill = director), 
                width = 0.1, 
                size = 2) +
  
  # This line includes the shade to the graph in the overlap of the confidence intervals
  geom_rect(xmin = 7.27, xmax = 7.33, ymin = 0, ymax = 10, fill = &quot;grey&quot;, aes(alpha = 0.1))+

  labs(
    title = &quot;Do Spielberg and Burton have the same IMDB ratings?&quot;,
    subtitle = &quot;95% confidence intervals overlap&quot;, 
    x = &quot;Mean IMDB ratings&quot;, 
    y = &quot;&quot;) +
  theme(plot.title = element_text(face = &quot;bold&quot;))
  
# Saving our graph
ggsave(&quot;graph_directors.jpg&quot;,
       plot=graph_directors,
       width = 10,height = 6, 
       path = here::here(&quot;images&quot;))

# Displaying the graph
knitr::include_graphics(here::here(&quot;images&quot;, &quot;graph_directors.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph_directors.jpg" width="1500" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Now, we want to select the date that we will use which is the rating and the directors
steve_tim &lt;- movies %&gt;% 
  select(rating, director) %&gt;% 
  filter(director %in% c(&quot;Tim Burton&quot;, &quot;Steven Spielberg&quot;)) 

# In this line we do the ttest with the previously selected data
t.test(rating ~ director, data = steve_tim)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<pre class="r"><code># In order to compare the two methods, we will run the test again using the &quot;infer&quot; package
obs_diff_IMBD &lt;- steve_tim %&gt;%
  specify(rating ~ director) %&gt;%
  calculate(
    stat = &quot;diff in means&quot;, 
    order = c(&quot;Tim Burton&quot;, &quot;Steven Spielberg&quot;))


null_dist_IMBD &lt;- steve_tim %&gt;%
  specify(rating ~ director) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(
    stat = &quot;diff in means&quot;, 
    order = c(&quot;Tim Burton&quot;, &quot;Steven Spielberg&quot;))


ggplot(data = null_dist_IMBD, 
       aes(
         x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/projects/project4/index_files/figure-html/unnamed-chunk-12-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist_IMBD %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff_IMBD, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/projects/project4/index_files/figure-html/unnamed-chunk-12-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist_IMBD %&gt;%
  get_p_value(obs_stat = obs_diff_IMBD, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1   0.006</code></pre>
<p><strong>Conclusion</strong>
Following our tests, we reject the null hypothesis as the p-value is under our treshold at 95% confidence interval. We can therefore conclude that there is a clear difference between the average rating between Steven Spielberg and Tim Burton. So clearly, Steven Spielberg’ movies have a higher rating than Tim Burton’s.</p>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>We are going to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, ...
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, ...
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24...</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>We will use multiple different types of analysis in order to conclude whether there is a significant difference between the salaries of the male and female executives at Omega Group Plc., including confidence intervals and hypothesis testing.</p>
<p>First, we will calculate summary statistics on salary by gender, by creating and printing a dataframe where, for each gender, we show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data=omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Creating data set with two rows (male-female)
salary_gender &lt;- omega %&gt;% 
  select (salary, gender) %&gt;% 
  group_by (gender)%&gt;%
  
  # Calculating mean, SD, sample size, the t-critical value, the standard error, the margin of error, and the low/high endpoints of a 95% confidence interval
  summarise (
          mean_salary = mean(salary, na.rm = TRUE),
          sd_salary = sd(salary, na.rm=TRUE),
          count = n(),
          se_salary = sd_salary/sqrt(count),
          t_critical = qt(0.975, count-1), 
          margin_of_error = t_critical * se_salary,
          lower = mean_salary - t_critical * se_salary,
          upper = mean_salary + t_critical * se_salary
            )

#Printing data set
salary_gender %&gt;% tbl_df %&gt;% rmarkdown::paged_table()</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["gender"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mean_salary"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sd_salary"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["count"],"name":[4],"type":["int"],"align":["right"]},{"label":["se_salary"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["t_critical"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["margin_of_error"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["lower"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["upper"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"female","2":"64543","3":"7567","4":"26","5":"1484","6":"2.06","7":"3056","8":"61486","9":"67599"},{"1":"male","2":"73239","3":"7463","4":"24","5":"1523","6":"2.07","7":"3151","8":"70088","9":"76390"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  #Plotting the data as a boxplot in order to better visualize the difference
  ggplot(data = na.omit(omega), 
         aes(
           x=gender, 
           y= salary, 
           color=gender))+
  
  # Arranging design of our graph
  geom_boxplot()+ 
  labs(
    title = &quot;Men tend to have higher salaries than women on average&quot;, 
    subtitle = &quot;Relationship between salary and gender&quot;,
    x =&quot;&quot;, 
    y =&quot;Salary&quot;)+
    theme_light()+
    theme(
  plot.title = element_text(color = &quot;snow4&quot;, size = 15, face = &quot;bold&quot;),
  plot.subtitle = element_text(color = &quot;salmon&quot;, size=10))</code></pre>
<p><img src="/projects/project4/index_files/figure-html/salary_gender_relationship-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>From our analysis above, we can conclude that on average, men do have higher salaries than women. Not only is the mean higher, but actually the lower quartile for men is just below the upper quartile for women. Nevertheless, this does not prove whether the difference is statistically significant, which is what we will explore in the next step.</p>
<p>We will now run a hypothesis testing. We assume the null hypothesis to be that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. Therefore, the alternative hypothesis is that, on average, men and women do not make the same amount of money, i.e. the mean difference in salaries is not zero.</p>
<pre class="r"><code># Hypothesis testing using t.test() 
t.test(salary ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<p>According to the data above, we can conclude that the difference is statistically significant, and therefore reject the null hypothesis. This is because the difference is greater than 4 standard deviations away from the mean (t=-4), as well as the fact that the 95% confidence interval does not pass through 0.</p>
<p>We will now run hypothesis testing using infer.</p>
<pre class="r"><code># Hypothesis testing using infer package

null_distance &lt;- omega %&gt;%
  specify(salary ~ gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(
    stat = &quot;diff in means&quot;, 
    order = c(&quot;female&quot;, &quot;male&quot;))

null_distance %&gt;%  visualize() + 
  shade_p_value(
    obs_stat = 2e-04, 
    direction = &quot;two-sided&quot;, 
    fill = &quot;royalblue&quot;) + 
  
  # Setting up the designing of the graph
  labs(
    title = &quot;Simulation-based Null Distributions&quot;, 
    x = &quot;Average Female - Average Male Salary&quot;, 
    y = &quot;Count&quot;, 
    subtitle = &quot;Observed differences marked in blue&quot;) +
  theme_light()+
  theme(
 plot.title = element_text(color = &quot;snow4&quot;, size = 15, face = &quot;bold&quot;),
 plot.subtitle = element_text(color = &quot;royalblue&quot;, size=10))</code></pre>
<p><img src="/projects/project4/index_files/figure-html/hypothesis_testing_infer-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>This is what we would see in a world equal pay for men and women. Regarding the t-test, we would expect to see a high p-value, failing to reject the null hypothesis and similar mean and distribution.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, we will explore whether we can conclude that there is a significant difference between the experience of the male and female executives.</p>
<pre class="r"><code># Creating data set with all necessary statistics

experience_gender &lt;- omega %&gt;% 
  
  #Selecting the variables of interest
  select (experience, gender) %&gt;% 
  
  # Grouping by gender
  group_by (gender)%&gt;%
  
  # Calculating the statistics of interest
  summarise (
          mean_experience = mean(experience, na.rm = TRUE),
            sd_experience = sd(experience, na.rm=TRUE),
            count = n(),
            se_experience = sd_experience/sqrt(count),
            t_critical = qt(0.975, count-1), 
            margin_of_error = t_critical * se_experience,
            lower = mean_experience - t_critical * se_experience,
            upper = mean_experience + t_critical * se_experience
            )

#Printing data set
experience_gender  %&gt;% tibble::as_tibble()</code></pre>
<pre><code>## # A tibble: 2 x 9
##   gender mean_experience sd_experience count se_experience t_critical
##   &lt;chr&gt;            &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt;         &lt;dbl&gt;      &lt;dbl&gt;
## 1 female            7.38          8.51    26          1.67       2.06
## 2 male             21.1          10.9     24          2.23       2.07
## # ... with 3 more variables: margin_of_error &lt;dbl&gt;, lower &lt;dbl&gt;, upper &lt;dbl&gt;</code></pre>
<pre class="r"><code>#Plotting the data as a boxplot in order to better visualize the difference

  ggplot(data = na.omit(omega), aes(x=gender, y= experience, color=gender))+
  geom_boxplot()+ 
  labs(
    title = &quot;Men are seen to have more experience than women on average&quot;, 
    subtitle = &quot;Relationship between experience and gender&quot;,
    x =&quot;&quot;, 
    y =&quot;Experience (Years)&quot;)+
    
    # Adjusting the design details of our plot
    theme_light()+
    theme(
  plot.title = element_text(color = &quot;snow4&quot;, size = 15, face = &quot;bold&quot;),
  plot.subtitle = element_text(color = &quot;salmon&quot;, size=10))</code></pre>
<p><img src="/projects/project4/index_files/figure-html/experience_gender_relationship-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The boxplot above illustrates that there may be a considerable difference in the average experience of men in the firm, in comparison to women. Nevertheless, in order to consider whether the difference is statistically significant, we will conduct a t-test.</p>
<p>Before running our t-test, we will assume the null hypothesis to be that the mean difference in experience is zero, or that, on average, men and women have the same number of years’ experience. Therefore, the alternative hypothesis is that, on average, men and women do not have the same amount of experience, i.e. the mean difference in experience is not zero.</p>
<pre class="r"><code># Hypothesis testing using t.test() 
t.test(experience ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<p>We can conclude that the difference is statistically significant, and therefore we can reject the null hypothesis. This is because the difference is greater than 5 standard deviations away from the mean (t=-5), as well as the fact that the 95% confidence interval does not pass through 0.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>We will analyze the relationship between salary and experience and draw a scatterplot to visually inspect the data.</p>
<pre class="r"><code># Correlation is interesting when scatterplotting data
corl &lt;- cor(omega$experience, omega$salary)

# Scatterplot creation
plot_salary_experience &lt;- ggplot(
  data = omega,
  aes(x = experience,
      y = salary,
      color = gender))+
  geom_point()+
  
  # Adding line of best fit
  geom_smooth(method = &quot;lm&quot;, color = &quot;black&quot;)+
  theme_bw() +
  
  # Designing the axes and titles
  labs(
    title = &quot;Salary is strongly and positively influenced by experience&quot;,
    subtitle = &quot;Plot salary vs. experience&quot;,
    x = &quot;Experience (in years)&quot;,
    y = &quot;Salary&quot;,
    caption = &quot;Source: Omega Group Plc.&quot;
  ) +
  
  # Showing the calculated correlation in our graph
  annotate(geom = &quot;text&quot;, 
           x = 23, 
           y = 0.5, 
           label = paste(&quot;Correlation = &quot;, 
                         round(corl, digits = 3)), size = 3) +
  
  # Adding dollar sign to y axis
  scale_y_continuous(label=dollar)

plot_salary_experience</code></pre>
<p><img src="/projects/project4/index_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The correlation of 0.803 highlights a strong and positive relation between the two variables. It thus seems that the experience of someone of Omega Group Plc. determines its level of salary.</p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/projects/project4/index_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>From the scatterplot of relationship between salary and experience, we can observe an obvious positive correlation between these two variables. This indicates that more experience in works leads to higher salary, which makes sense in real life.
Based on this conclusion, we have to reconsider our assumption that women are discriminated in companies. Salaries are determined by not only gender but also experience, which means lower salaries for women may be attributed to their lower experience. In order to find out real relationship between salary and gender, we have to control the variety of experience or regress salary on both gender and experience at the same time.</p>
</div>
</div>
<div id="challenge-1-yield-curve-inversion" class="section level1">
<h1>Challenge 1: Yield Curve inversion</h1>
<p>Every so often, we hear warnings from commentators on the “inverted yield curve” and its predictive power with respect to recessions. An explainer what a <a href="https://www.reuters.com/article/us-usa-economy-yieldcurve-explainer/explainer-what-is-an-inverted-yield-curve-idUSKBN1O50GA">inverted yield curve is can be found here</a>. If you’d rather listen to something, here is a great podcast from <a href="https://www.podbean.com/media/share/dir-4zgj9-6aefd11">NPR on yield curve indicators</a></p>
<p>In addition, many articles and commentators think that, e.g., <a href="https://www.bloomberg.com/news/articles/2019-08-14/u-k-yield-curve-inverts-for-first-time-since-financial-crisis"><em>Yield curve inversion is viewed as a harbinger of recession</em></a>. One can always doubt whether inversions are truly a harbinger of recessions, and <a href="https://twitter.com/5_min_macro/status/1161627360946511873">use the attached parable on yield curve inversions</a>.</p>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/yield_curve_parable.jpg" width="100%" style="display: block; margin: auto;" /></p>
<p>In our case we will look at US data and use the <a href="https://fred.stlouisfed.org/">FRED database</a> to download historical yield curve rates, and plot the yield curves since 1999 to see when the yield curves flatten. If you want to know more, a very nice article that explains the <a href="https://fredblog.stlouisfed.org/2018/10/the-data-behind-the-fear-of-yield-curve-inversions/">yield curve is and its inversion can be found here</a>. At the end of this chllenge you should produce this chart</p>
<p>First, we will use the <code>tidyquant</code> package to download monthly rates for different durations.</p>
<pre class="r"><code># Get a list of FRED codes for US rates and US yield curve; choose monthly frequency
# to see, eg., the 3-month T-bill https://fred.stlouisfed.org/series/TB3MS
tickers &lt;- c(&#39;TB3MS&#39;, # 3-month Treasury bill (or T-bill)
             &#39;TB6MS&#39;, # 6-month
             &#39;GS1&#39;,   # 1-year
             &#39;GS2&#39;,   # 2-year, etc....
             &#39;GS3&#39;,
             &#39;GS5&#39;,
             &#39;GS7&#39;,
             &#39;GS10&#39;,
             &#39;GS20&#39;,
             &#39;GS30&#39;)  #.... all the way to the 30-year rate

# Turn  FRED codes to human readable variables
myvars &lt;- c(&#39;3-Month Treasury Bill&#39;,
            &#39;6-Month Treasury Bill&#39;,
            &#39;1-Year Treasury Rate&#39;,
            &#39;2-Year Treasury Rate&#39;,
            &#39;3-Year Treasury Rate&#39;,
            &#39;5-Year Treasury Rate&#39;,
            &#39;7-Year Treasury Rate&#39;,
            &#39;10-Year Treasury Rate&#39;,
            &#39;20-Year Treasury Rate&#39;,
            &#39;30-Year Treasury Rate&#39;)

maturity &lt;- c(&#39;3m&#39;, &#39;6m&#39;, &#39;1y&#39;, &#39;2y&#39;,&#39;3y&#39;,&#39;5y&#39;,&#39;7y&#39;,&#39;10y&#39;,&#39;20y&#39;,&#39;30y&#39;)

# by default R will sort these maturities alphabetically; but since we want
# to keep them in that exact order, we recast maturity as a factor 
# or categorical variable, with the levels defined as we want
maturity &lt;- factor(maturity, levels = maturity)

# Create a lookup dataset
mylookup&lt;-data.frame(symbol=tickers,var=myvars, maturity=maturity)
# Take a look:
mylookup %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">symbol</th>
<th align="left">var</th>
<th align="left">maturity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">TB3MS</td>
<td align="left">3-Month Treasury Bill</td>
<td align="left">3m</td>
</tr>
<tr class="even">
<td align="left">TB6MS</td>
<td align="left">6-Month Treasury Bill</td>
<td align="left">6m</td>
</tr>
<tr class="odd">
<td align="left">GS1</td>
<td align="left">1-Year Treasury Rate</td>
<td align="left">1y</td>
</tr>
<tr class="even">
<td align="left">GS2</td>
<td align="left">2-Year Treasury Rate</td>
<td align="left">2y</td>
</tr>
<tr class="odd">
<td align="left">GS3</td>
<td align="left">3-Year Treasury Rate</td>
<td align="left">3y</td>
</tr>
<tr class="even">
<td align="left">GS5</td>
<td align="left">5-Year Treasury Rate</td>
<td align="left">5y</td>
</tr>
<tr class="odd">
<td align="left">GS7</td>
<td align="left">7-Year Treasury Rate</td>
<td align="left">7y</td>
</tr>
<tr class="even">
<td align="left">GS10</td>
<td align="left">10-Year Treasury Rate</td>
<td align="left">10y</td>
</tr>
<tr class="odd">
<td align="left">GS20</td>
<td align="left">20-Year Treasury Rate</td>
<td align="left">20y</td>
</tr>
<tr class="even">
<td align="left">GS30</td>
<td align="left">30-Year Treasury Rate</td>
<td align="left">30y</td>
</tr>
</tbody>
</table>
<pre class="r"><code>df &lt;- tickers %&gt;% tidyquant::tq_get(get=&quot;economic.data&quot;, 
                   from=&quot;1960-01-01&quot;)   # start from January 1960

glimpse(df)</code></pre>
<pre><code>## Rows: 6,774
## Columns: 3
## $ symbol &lt;chr&gt; &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS...
## $ date   &lt;date&gt; 1960-01-01, 1960-02-01, 1960-03-01, 1960-04-01, 1960-05-01,...
## $ price  &lt;dbl&gt; 4.35, 3.96, 3.31, 3.23, 3.29, 2.46, 2.30, 2.30, 2.48, 2.30, ...</code></pre>
<p>Our dataframe <code>df</code> has three columns (variables):</p>
<ul>
<li><code>symbol</code>: the FRED database ticker symbol</li>
<li><code>date</code>: already a date object</li>
<li><code>price</code>: the actual yield on that date</li>
</ul>
<p>The first thing would be to join this dataframe <code>df</code> with the dataframe <code>mylookup</code> so we have a more readable version of maturities, durations, etc.</p>
<pre class="r"><code>yield_curve &lt;-left_join(df,mylookup,by=&quot;symbol&quot;) </code></pre>
<div id="yields-on-us-rates-by-duration-since-1960" class="section level3">
<h3>Yields on US rates by duration since 1960</h3>
<pre class="r"><code>yield_curve$var &lt;- factor(yield_curve$var, levels = c(
            &#39;3-Month Treasury Bill&#39;,
            &#39;6-Month Treasury Bill&#39;,
            &#39;1-Year Treasury Rate&#39;,
            &#39;2-Year Treasury Rate&#39;,
            &#39;3-Year Treasury Rate&#39;,
            &#39;5-Year Treasury Rate&#39;,
            &#39;7-Year Treasury Rate&#39;,
            &#39;10-Year Treasury Rate&#39;,
            &#39;20-Year Treasury Rate&#39;,
            &#39;30-Year Treasury Rate&#39;))

graph1_challenge1 &lt;- ggplot(yield_curve,
       
      #♥Setting up the axis                      
      aes(
         x = date, 
         y = price, 
         colour = var)) +
         
  # Plotting data as lines
  geom_line() + 
  
  # Facetting to see by var       
  facet_wrap(~var, ncol = 2 ) + 
        
  # Adjusting the design and description of our graph
  theme_bw() + 
  theme(legend.position = &quot;none&quot;) + 
        labs(
          caption = &quot;Source: St. Louis federal Reserve Economic Database (FRED)&quot;, 
          title = &quot;Yield on US Treasury rates since 1960&quot;, 
          y = &quot;%&quot;, 
          x = &quot;&quot;)
        
# This line saves the graph as a .jpg file
ggsave(&quot;graph1_challenge1.jpg&quot;,plot=graph1_challenge1,width = 10,height = 8, dpi = 200, path = here::here(&quot;images&quot;))

# And this line includes the above mentioned picture in the HTML knited file
knitr::include_graphics(here::here(&quot;images&quot;,&quot;graph1_challenge1.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph1_challenge1.jpg" width="1000" style="display: block; margin: auto;" /></p>
</div>
<div id="monthly-yields-on-us-rates-by-duration-since-1999-on-a-year-by-year-basis" class="section level3">
<h3>Monthly yields on US rates by duration since 1999 on a year-by-year basis</h3>
<pre class="r"><code>copy &lt;- data.frame(yield_curve)
# Creating a variable with only the year of the date.
copy$year &lt;- as.numeric(format(df$date, &quot;%Y&quot;))

# Creating a new dataset for the following graph.
yield_curve_1999 &lt;- copy %&gt;% 
  
  # Selecting only the years we are interested in for our graph.
  filter(year %in% (1999:2020))

# Replicating the graph
graph2_challenge1 &lt;- ggplot(yield_curve_1999,
  
  # Setting the axes and aestetics.                        
  aes(
    x = maturity, 
    y = price, 
    color = year)) + 
  
  # Specifying which data we wish to be linked.
  # Default would be by maturity.
  # We linked by date to follow the trends.
  geom_line(aes(group = date)) +
  
  # Wrapping by year and organizing our graphs.
  facet_wrap(~year, ncol = 4 ) + 
  
  # Setting the appropriate theme.
  theme_bw() + 
  
  # Removing the legend.
  theme(legend.position = &quot;none&quot;) + 
  
  # Naming the axes
  labs(
    title = &quot;US Yield Curve&quot;,
    caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;, 
    x = &quot;Maturity&quot;, 
    y = &quot;Yield (%)&quot;
  ) +
  
  # Changing the colors from gradient blue to rainbow.
  scale_colour_gradientn(colours=rainbow(4))
           

# This line saves the graph as a .jpg file
ggsave(&quot;graph2_challenge1.jpg&quot;,width = 15,height = 10, dpi = 150, path = here::here(&quot;images&quot;))

# And this line includes the above mentioned picture in the HTML knited file
knitr::include_graphics(here::here(&quot;images&quot;,&quot;graph2_challenge1.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph2_challenge1.jpg" width="1125" style="display: block; margin: auto;" /></p>
</div>
<div id="month-and-10-year-yields-since-1999" class="section level3">
<h3>3-month and 10-year yields since 1999</h3>
<pre class="r"><code>yield_curve_3m_10y &lt;- copy %&gt;% 
  
  # Selecting only the 3-month and 10-year maturity
  filter(maturity %in% c(&quot;3m&quot;, &quot;10y&quot;)) %&gt;% 
  # Selecting only the years we are interested in for our graph.
  filter(year %in% (1999:2020))

# Replicating the graph
graph3_challenge1 &lt;- ggplot(yield_curve_3m_10y,
  
  # Setting up the axes and colors.                          
  aes(
    x = date, 
    y = price, 
    color = maturity
  )) +
  
  # Linking the data by maturity. 
  geom_line() +
  
  # Setting up the theme and base size of the texts in the graph. 
  theme_bw(base_size = 9) +
  
  # Setting the title, axes, and caption.
  labs(
    title = &quot;Yields on 3-month and 10-year US Treasury rates since 1999&quot;,
    caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;, 
    x = &quot;&quot;,
    y = &quot;%&quot;
  ) +
  
  # Changing the names to display in the legend.
  scale_colour_discrete(
    name=&quot;&quot;, # Removing the legend title.
    labels=c(&quot;3-Month Treasury Bill&quot;, &quot;10-Year Treasury Rate&quot;))


# This line saves the graph as a .jpg file
ggsave(&quot;graph3_challenge1.jpg&quot;,width = 10,height = 8, dpi = 150, path = here::here(&quot;images&quot;))

# And this line includes the above mentioned picture in the HTML knited file
knitr::include_graphics(here::here(&quot;images&quot;,&quot;graph3_challenge1.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph3_challenge1.jpg" width="750" style="display: block; margin: auto;" /></p>
<p>According to <a href="https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States">Wikipedia’s list of recession in the United States</a>, since 1999 there have been two recession in the US: between Mar 2001–Nov 2001 and between Dec 2007–June 2009. Does the yield curve seem to flatten before these recessions? Can a yield curve flattening really mean a recession is coming in the US? Since 1999, when did short-term (3 months) yield more than longer term (10 years) debt?</p>
<p>Besides calculating the spread (10year - 3months), there are a few things we need to do to produce our final plot</p>
<ol style="list-style-type: decimal">
<li>Setup data for US recessions</li>
<li>Superimpose recessions as the grey areas in our plot</li>
<li>Plot the spread between 30 years and 3 months as a blue/red ribbon, based on whether the spread is positive (blue) or negative(red)</li>
</ol>
<ul>
<li>For the first, the code below creates a dataframe with all US recessions since 1946</li>
</ul>
<pre class="r"><code># get US recession dates after 1946 from Wikipedia 
# https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States

recessions &lt;- tibble(
  from = c(&quot;1960-04-01&quot;, &quot;1969-12-01&quot;, &quot;1973-11-01&quot;, &quot;1980-01-01&quot;,&quot;1981-07-01&quot;, &quot;1990-07-01&quot;, &quot;2001-03-01&quot;, &quot;2007-12-01&quot;),  
  to = c(&quot;1961-02-01&quot;, &quot;1970-11-01&quot;, &quot;1975-03-01&quot;, &quot;1980-07-01&quot;, &quot;1982-11-01&quot;, &quot;1991-03-01&quot;, &quot;2001-11-01&quot;, &quot;2009-06-01&quot;) 
  )  %&gt;% 
  mutate(From = ymd(from), 
         To=ymd(to),
         duration_days = To-From)

recessions</code></pre>
<pre><code>## # A tibble: 8 x 5
##   from       to         From       To         duration_days
##   &lt;chr&gt;      &lt;chr&gt;      &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;       
## 1 1960-04-01 1961-02-01 1960-04-01 1961-02-01 306 days     
## 2 1969-12-01 1970-11-01 1969-12-01 1970-11-01 335 days     
## 3 1973-11-01 1975-03-01 1973-11-01 1975-03-01 485 days     
## 4 1980-01-01 1980-07-01 1980-01-01 1980-07-01 182 days     
## 5 1981-07-01 1982-11-01 1981-07-01 1982-11-01 488 days     
## 6 1990-07-01 1991-03-01 1990-07-01 1991-03-01 243 days     
## 7 2001-03-01 2001-11-01 2001-03-01 2001-11-01 245 days     
## 8 2007-12-01 2009-06-01 2007-12-01 2009-06-01 548 days</code></pre>
<pre class="r"><code># Since we only need the 3-month and 10-year prices, we erased the columns maturity and symbol to use pivot_wider and calculate the difference between these two curves in line 372

yield_curve$maturity = NULL
yield_curve$symbol = NULL

yield_curve_2 &lt;- yield_curve %&gt;% 
  filter(var %in% c(&quot;3-Month Treasury Bill&quot;,
            &quot;10-Year Treasury Rate&quot;)) %&gt;% 
  pivot_wider(names_from = var , 
              values_from = price)


 colnames(yield_curve_2)&lt;- c(&quot;date&quot;,&quot;Three_Month&quot;,&quot;Ten_year&quot;)


  yield_curve_2 &lt;- yield_curve_2 %&gt;% 
  mutate(difference_recession = Ten_year - Three_Month) %&gt;% 
  
  
  # This new column will be used to fill the graph in red or green
   mutate(change = if_else(difference_recession&gt;=0, &quot;Above&quot;, &quot;Below&quot;))%&gt;% 

  
  mutate(rug_colour = if_else(change==&quot;Below&quot;,&quot;#DEAFB1&quot;,&quot;#BEEBC2&quot;))


  
graph_1 &lt;- ggplot(yield_curve_2, 
                  aes(x = date,
                      y= difference_recession*100)) +
  
  geom_line()+
  
  #This line includes the horizontal line in the graph
  geom_hline(yintercept=0)+
  
  #These two next lines include the filling in red or green in the graph
  geom_ribbon(aes(ymin = 0, 
                  ymax = pmin(0,difference_recession*100), 
                  fill = &quot;Above&quot;)) + 
  
geom_ribbon(aes(ymin = difference_recession*100, 
                ymax = pmin(0,difference_recession*100), 
                fill = &quot;Below&quot;))+
  
  #We used geom_rect to shade in grey the moments in which there were recessions
geom_rect(data= recessions,
          inherit.aes=F,
          aes(xmin= From , xmax= To, ymin=-Inf, ymax=+Inf),
          fill = &quot;grey&quot;,
          alpha=0.5)+
  
# These lines include the rug and change it&#39;s colours by the column rug_colour
  geom_rug(color = yield_curve_2$rug_colour,
           sides=&quot;b&quot;) +

  scale_fill_manual(values = c(&quot;#DEAFB1&quot;,&quot;#BEEBC2&quot;,&quot;grey&quot;,&quot;white&quot;))+
  
  
  #Adjusting the design
  theme_bw()+
  
  theme(axis.ticks = element_blank())+
  
  # Removing the legend
  theme(legend.position = &quot;none&quot;) + 
  theme(panel.border = element_blank())+
 
  # labeling the axes
  labs(x = &quot;&quot;, 
       y = &quot;Difference (10 years - 3 month) yield in %&quot;, 
       title = &quot;Yield Curve Inversion: 10-year minus 3-month U.S. Treasury rates&quot;, 
       subtitle = &quot;Difference in % points, monthly averages.\n Shaded areas correspond to recessions&quot;, 
       caption = &quot;Source: St.Louis Federal Reserve Economic Database(FRED)&quot;)+
  
  # Title in bold
  theme(plot.title = element_text(face = &quot;bold&quot;))


# This line saves the graph as a .jpg file
ggsave(&quot;graph_1.jpg&quot;,plot=graph_1,width = 8,height = 5,dpi=200, path = here::here(&quot;images&quot;))


# # And this line includes the above mentioned picture in the HTML knited file
knitr::include_graphics(here::here(&quot;images&quot;,&quot;graph_1.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph_1.jpg" width="800" style="display: block; margin: auto;" /></p>
<ul>
<li>To add the grey shaded areas corresponding to recessions, we use <code>geom_rect()</code></li>
<li>to colour the ribbons blue/red we must see whether the spread is positive or negative and then use <code>geom_ribbon()</code>.</li>
</ul>
</div>
</div>
<div id="challenge-2gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2:GDP components over time and among countries</h1>
<p>At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">Wikipedia GDP page</a>.</p>
<pre class="r"><code>UN_GDP_data  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=2) # Number of rows to skip</code></pre>
<p>The first thing we need to do is to tidy the data, as it is in wide format and we must make it into long, tidy format. Please express all figures in billions (divide values by <code>1e9</code>, or <span class="math inline">\(10^9\)</span>), and we want to rename the indicators into something shorter.</p>
<pre class="r"><code># Change the data from a wide to long format

tidy_GDP_data  &lt;-  UN_GDP_data %&gt;%
  pivot_longer(cols = (4:51), names_to = &quot;Year&quot;, values_to = &quot;Total&quot;) %&gt;% 
  mutate(&quot;Total&quot; = Total/1e9) %&gt;% 
  mutate(Year = as.numeric(Year))

old_indicators &lt;- c(&quot;Final consumption expenditure&quot;, 
                    &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;, 
                    &quot;General government final consumption expenditure&quot;, 
                    &quot;Gross capital formation&quot;, 
                    &quot;Gross fixed capital formation (including Acquisitions less disposals of valuables)&quot;,
                    &quot;Exports of goods and services&quot;, 
                    &quot;Imports of goods and services&quot;,
                    &quot;Gross Domestic Product (GDP)&quot;, 
                    &quot;Agriculture, hunting, forestry, fishing (ISIC A-B)&quot;, 
                    &quot;Mining, Manufacturing, Utilities (ISIC C-E)&quot;,
                    &quot;Manufacturing (ISIC D)&quot;, 
                    &quot;Construction (ISIC F)&quot;,
                    &quot;Wholesale, retail trade, restaurants and hotels (ISIC G-H)&quot;, 
                    &quot;Transport, storage and communication (ISIC I)&quot;, 
                    &quot;Other Activities (ISIC J-P)&quot;, 
                    &quot;Total Value Added&quot;)

new_indicators &lt;- tidy_GDP_data %&gt;% 
  filter(IndicatorName %in% old_indicators) %&gt;% 
  pivot_wider(names_from = IndicatorName, values_from = Total)

names(new_indicators)[4:19] &lt;- c(&quot;FCE&quot;, &quot;HCE&quot;, &quot;GGFCE&quot;, &quot;GCF&quot;, &quot;GFCF&quot;, &quot;EGS&quot;, &quot;IGS&quot;, &quot;GDP&quot;, &quot;AHFF&quot;, &quot;MMU&quot;,&quot;MFG&quot;, &quot;CTN&quot;, &quot;WRR&quot;, &quot;TSC&quot;, &quot;OA&quot;, &quot;TVA&quot;)

glimpse(new_indicators)</code></pre>
<pre><code>## Rows: 10,560
## Columns: 19
## $ CountryID &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...
## $ Country   &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan...
## $ Year      &lt;dbl&gt; 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 197...
## $ FCE       &lt;dbl&gt; 5.56, 5.33, 5.20, 5.75, 6.15, 6.32, 6.37, 6.90, 7.09, 6.9...
## $ HCE       &lt;dbl&gt; 5.07, 4.84, 4.70, 5.21, 5.59, 5.65, 5.68, 6.15, 6.30, 6.1...
## $ GGFCE     &lt;dbl&gt; 0.372, 0.382, 0.402, 0.421, 0.431, 0.598, 0.627, 0.676, 0...
## $ GCF       &lt;dbl&gt; 0.985, 1.050, 0.919, 0.919, 1.181, 1.365, 2.035, 1.917, 2...
## $ GFCF      &lt;dbl&gt; 0.985, 1.050, 0.919, 0.919, 1.181, 1.365, 2.035, 1.917, 2...
## $ EGS       &lt;dbl&gt; 0.112, 0.145, 0.173, 0.218, 0.300, 0.316, 0.417, 0.431, 0...
## $ IGS       &lt;dbl&gt; 0.184, 0.269, 0.260, 0.278, 0.407, 0.459, 0.564, 0.679, 0...
## $ GDP       &lt;dbl&gt; 10.72, 10.69, 8.94, 9.20, 9.70, 10.30, 10.86, 10.32, 11.0...
## $ AHFF      &lt;dbl&gt; 7.99, 7.68, 7.36, 7.90, 8.18, 8.45, 8.82, 7.87, 8.35, 8.5...
## $ MMU       &lt;dbl&gt; 1.006, 1.053, 1.102, 1.152, 1.269, 1.390, 1.424, 1.478, 1...
## $ MFG       &lt;dbl&gt; 0.982, 1.029, 1.076, 1.123, 1.237, 1.356, 1.389, 1.441, 1...
## $ CTN       &lt;dbl&gt; 0.0460, 0.0460, 0.0484, 0.0556, 0.0556, 0.0783, 0.1174, 0...
## $ WRR       &lt;dbl&gt; 0.444, 0.403, 0.399, 0.476, 0.505, 0.533, 0.557, 0.524, 0...
## $ TSC       &lt;dbl&gt; 0.254, 0.231, 0.229, 0.273, 0.331, 0.397, 0.438, 0.496, 0...
## $ OA        &lt;dbl&gt; 0.446, 0.405, 0.401, 0.478, 0.505, 0.531, 0.558, 0.531, 0...
## $ TVA       &lt;dbl&gt; 9.59, 9.25, 8.99, 9.75, 10.23, 10.76, 11.28, 10.49, 11.17...</code></pre>
<pre class="r"><code># Let us compare GDP components for these 4 countries
country_list &lt;- c(&quot;United States&quot;,&quot;India&quot;, &quot;Germany&quot;, &quot;Belgium&quot;)</code></pre>
<pre class="r"><code>plot_indicators &lt;- c(&quot;Gross capital formation&quot;, 
                     &quot;Exports of goods and services&quot;,
                     &quot;General government final consumption expenditure&quot;, 
                     &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
                     &quot;Imports of goods and services&quot;)

 # Selecting the countries and variable of interest.
GDP_indicators &lt;- tidy_GDP_data %&gt;% 
  filter(Country %in% country_list) %&gt;% 
  filter(IndicatorName %in% plot_indicators)

# Reordering our variables for the legend in the graph
GDP_indicators$IndicatorName &lt;- factor(GDP_indicators$IndicatorName, 
                                       levels = c(
                                         &quot;Gross capital formation&quot;, 
                                         &quot;Exports of goods and services&quot;,
                                         &quot;General government final consumption expenditure&quot;, 
                                         &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;, 
                                         &quot;Imports of goods and services&quot;))

# Creating the graph
GDPplot &lt;- ggplot(data = GDP_indicators, 
                  aes(
                    x = Year, 
                    y = Total, 
                    color = IndicatorName))+
  geom_line()+
  facet_wrap(~Country, ncol = 4)+
  
    # Adjusting the names displayed in the legend and its title
  scale_colour_discrete(
    name=&quot;Components of GDP&quot;,
    labels=c(&quot;Gross capital formation&quot;, 
             &quot;Exports&quot;, 
             &quot;Government expenditure&quot;, 
             &quot;Household expenditure&quot;, 
             &quot;Imports&quot;)) +
  
  # Designing the axes and design
  labs(
     x = &quot;&quot;, 
     y = &quot;Billion US$&quot;, 
     title = &quot;GDP components over time&quot;, 
     subtitle = &quot;In constant 2010 USD&quot;)+
  theme(legend.position = &quot;right&quot;)+
  theme_bw()+
                     

 # This line saves the graph as a .jpg file
ggsave(&quot;graph_c2.jpg&quot;,width = 10,height = 6,dpi=200, path = here::here(&quot;images&quot;))


# # And this line includes the above mentioned picture in the HTML knited file
knitr::include_graphics(here::here(&quot;images&quot;,&quot;graph_c2.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph_c2.jpg" width="1000" style="display: block; margin: auto;" /></p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<p>We also look later at the % difference between what we calculated as GDP and the GDP figure included in the dataframe.</p>
<pre class="r"><code>gdpcomponent &lt;- c(&quot;Gross capital formation&quot;, 
                  &quot;Exports of goods and services&quot;,    

                  &quot;General government final consumption expenditure&quot;, 
                  &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
                  &quot;Imports of goods and services&quot;, 
                  &quot;Gross Domestic Product (GDP)&quot;)

task2 &lt;- new_indicators %&gt;% 
  mutate(&quot;caculatedGDP&quot; = HCE + GGFCE + GCF + EGS - IGS, 
         &quot;difference&quot; = (GDP - caculatedGDP) / GDP ) 

# Selecting our list of countris
task2_3countries &lt;- task2 %&gt;% 
  filter(Country %in% country_list)

# Creating the graph
task2plot &lt;- ggplot(
  data = task2_3countries, 
  aes(
    x = Year, 
    y = difference)) + 

  # Designing the graph 
  facet_wrap(~Country, ncol = 4)+
  geom_line(color = &quot;lightblue&quot;, size = 1)+
  scale_y_continuous(labels = scales::percent_format())+
  theme_bw()+
  labs(
    y = &quot;Difference between reported and calculated GDP &quot;,
    subtitle = &quot; GDP vs. Calculated GDP&quot;)
  

  # This line saves the graph as a .jpg file
ggsave(&quot;graph_c2_3.jpg&quot;,plot=task2plot,width = 10,height = 6,dpi=200, path = here::here(&quot;images&quot;))


# # And this line includes the above mentioned picture in the HTML knited file
knitr::include_graphics(here::here(&quot;images&quot;,&quot;graph_c2_3.jpg&quot;))</code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/graph_c2_3.jpg" width="1000" style="display: block; margin: auto;" /></p>
<p>Comment:
Germany, Belgium, and the United States experience very similiar trends in terms of the convergence between GDP and caculated GDP while India remains volaties.</p>
<p>It may reflect that developed countries represented by Germany, Belgium, and United States have developed and refined their economics statistics, narrowing the gap. While emerging markets including India still have a long way to go.</p>
<pre class="r"><code># Calculating the required variables
task2 &lt;- new_indicators %&gt;% 
  mutate(&quot;NetExport&quot; = EGS - IGS) %&gt;% 
  mutate(&quot;NEper&quot; = NetExport / GDP) %&gt;% 
  mutate(&quot;CAPITALper&quot; = GCF / GDP) %&gt;% 
  mutate(&quot;HOUSEHOLDper&quot; = HCE / GDP) %&gt;% 
  mutate(&quot;GOVERNMENTper&quot; = GGFCE / GDP) %&gt;% 
  select(NEper,CAPITALper,HOUSEHOLDper,GOVERNMENTper,Country,Year)

task2_3countries &lt;- task2 %&gt;% 
  filter(Country %in% country_list)

task2_breakdown &lt;- task2_3countries %&gt;% 
pivot_longer(cols = (1:4), 
             names_to = &quot;Breakdown&quot;, 
             values_to = &quot;propotion&quot;) 

# Reordering our variable 
task2_breakdown$Breakdown &lt;- factor(task2_breakdown$Breakdown, 
                                       levels = c(
                                         &quot;GOVERNMENTper&quot;, 
                                         &quot;CAPITALper&quot;,
                                         &quot;HOUSEHOLDper&quot;, 
                                         &quot;NEper&quot;))
# Creating the graph
task2plot &lt;- ggplot(data = task2_breakdown, 
                    
                    # Setting up the axes and group
                    aes(
                      x = Year, 
                      y = propotion, 
                      group = Breakdown, 
                      color = Breakdown)) + 
  
  # Adjsuting the test in the legend
  scale_color_discrete(
            name=&quot;&quot;,
            labels = c(&quot;Government Expenditure&quot;,
            &quot;Gross capital formation&quot;,
            &quot;Household Expenditure&quot;,
            &quot;Net Exports&quot;))+
  
  # Wrap by country and have the four graph on one line
  facet_wrap(~Country, ncol = 4) + 
 
  # Making the line a bit thicker
  geom_line(size = 0.8)+
  
  # Adding % signs and adjusting the limits for the y axis
  scale_y_continuous(
    labels = scales::percent_format(),
    limits = c(-0.1,0.8))+
  
  # Choosing our theme and increasing the size of the text
  theme_bw(base_size = 20)+
  
  # Setting up the descriptive elements
  labs(
    x = &quot;&quot;,
    y = &quot;propotion&quot;, 
    subtitle = &quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;,
    caption = &quot;Source: United Nations, https://unstats.un.org/unsd/snaama/Downloads&quot; )+
  
  
  #theme(legend.position = &quot;right&quot;)

#save pic
ggsave(&quot;task2.jpg&quot;,width = 20,height = 9, path = here::here(&quot;images&quot;))

#add to code
knitr::include_graphics(here::here(&quot;images&quot;, &quot;task2.jpg&quot;))  </code></pre>
<p><img src="C:/Users/NOEL%20Jules/Music/Data%20Analysis/Individual%20Web%20Portfolio/my_website/images/task2.jpg" width="3000" style="display: block; margin: auto;" /></p>
<p>All three countries have highest proportion for Household Expenditure and lowest of net export, revealing a basic economic pattern and principle.</p>
<p>Germany, Belgium and United States share more similar patterns perhaps because both are developed economies and have similar economy structure. The proportion change across different GDP components are also relatively stable due to their economic maturity.</p>
<p>India has an obvious convergence since 2000 when its proportion of net export rised while that of household expenditure shrinked, indicating its fast economic growth and transition, and a focus on ‘export economies’</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: Group 26</li>
<li>Approximately how much time did you spend on this problem set: 20 hours</li>
<li>What, if anything, gave you the most trouble: Graph with the recessions</li>
</ul>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
